version: '3.9'

networks:
  api-network:


services:

  mysql_devbook:
    image: mysql:latest
    container_name: mysql_devbook
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306

    volumes:
      # - ./mysql:/var/lib/mysql
      - ./api_devbook/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api-network
    expose:
      - 3306

  api_devbook:
    depends_on:
      - mysql_devbook
    build:
      context: ./api_devbook
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: api_devbook
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - api-network
